INSERT INTO stock (Symbol, Name) VALUES 
('ABB', 'ABB India Ltd.'), 
('ADANIENSOL', 'Adani Energy Solutions Ltd.'), 
('ADANIENT', 'Adani Enterprises Ltd.'), 
('ADANIGREEN', 'Adani Green Energy Ltd.'), 
('ADANIPORTS', 'Adani Ports and Special Economic Zone Ltd.'), 
('ADANIPOWER', 'Adani Power Ltd.'), 
('ATGL', 'Adani Total Gas Ltd.'), 
('AMBUJACEM', 'Ambuja Cements Ltd.'), 
('APOLLOHOSP', 'Apollo Hospitals Enterprise Ltd.'), 
('ASIANPAINT', 'Asian Paints Ltd.'), 
('DMART', 'Avenue Supermarts Ltd.'), 
('AXISBANK', 'Axis Bank Ltd.'), 
('BAJAJ-AUTO', 'Bajaj Auto Ltd.'), 
('BAJFINANCE', 'Bajaj Finance Ltd.'), 
('BAJAJFINSV', 'Bajaj Finserv Ltd.'), 
('BAJAJHLDNG', 'Bajaj Holdings & Investment Ltd.'), 
('BANKBARODA', 'Bank of Baroda'), 
('BERGEPAINT', 'Berger Paints India Ltd.'), 
('BEL', 'Bharat Electronics Ltd.'), 
('BPCL', 'Bharat Petroleum Corporation Ltd.'), 
('BHARTIARTL', 'Bharti Airtel Ltd.'), 
('BOSCHLTD', 'Bosch Ltd.'), 
('BRITANNIA', 'Britannia Industries Ltd.'), 
('CANBK', 'Canara Bank'), 
('CIPLA', 'Cipla Ltd.'), 
('COALINDIA', 'Coal India Ltd.'), 
('COLPAL', 'Colgate Palmolive (India) Ltd.'), 
('DLF', 'DLF Ltd.'), 
('DABUR', 'Dabur India Ltd.'), 
('DIVISLAB', 'Divi\'s Laboratories Ltd.'), 
('DRREDDY', 'Dr. Reddy\'s Laboratories Ltd.'), 
('EICHERMOT', 'Eicher Motors Ltd.'), 
('GAIL', 'GAIL (India) Ltd.'), 
('GODREJCP', 'Godrej Consumer Products Ltd.'), 
('GRASIM', 'Grasim Industries Ltd.'), 
('HCLTECH', 'HCL Technologies Ltd.'), 
('HDFCBANK', 'HDFC Bank Ltd.'), 
('HDFCLIFE', 'HDFC Life Insurance Company Ltd.'), 
('HAVELLS', 'Havells India Ltd.'), 
('HEROMOTOCO', 'Hero MotoCorp Ltd.'), 
('HINDALCO', 'Hindalco Industries Ltd.'), 
('HAL', 'Hindustan Aeronautics Ltd.'), 
('HINDUNILVR', 'Hindustan Unilever Ltd.'), 
('ICICIBANK', 'ICICI Bank Ltd.'), 
('ICICIGI', 'ICICI Lombard General Insurance Company Ltd.'), 
('ICICIPRULI', 'ICICI Prudential Life Insurance Company Ltd.'), 
('ITC', 'ITC Ltd.'), 
('IOC', 'Indian Oil Corporation Ltd.'), 
('IRCTC', 'Indian Railway Catering And Tourism Corporation Ltd.'), 
('IRFC', 'Indian Railway Finance Corporation Ltd.'), 
('INDUSINDBK', 'IndusInd Bank Ltd.'), 
('NAUKRI', 'Info Edge (India) Ltd.'), 
('INFY', 'Infosys Ltd.'), 
('INDIGO', 'InterGlobe Aviation Ltd.'), 
('JSWSTEEL', 'JSW Steel Ltd.'), 
('JINDALSTEL', 'Jindal Steel & Power Ltd.'), 
('JIOFIN', 'Jio Financial Services Ltd.'), 
('KOTAKBANK', 'Kotak Mahindra Bank Ltd.'), 
('LTIM', 'LTIMindtree Ltd.'), 
('LT', 'Larsen & Toubro Ltd.'), 
('LICI', 'Life Insurance Corporation of India'), 
('M&M', 'Mahindra & Mahindra Ltd.'), 
('MARICO', 'Marico Ltd.'), 
('MARUTI', 'Maruti Suzuki India Ltd.'), 
('NTPC', 'NTPC Ltd.'), 
('NESTLEIND', 'Nestle India Ltd.'), 
('ONGC', 'Oil & Natural Gas Corporation Ltd.'), 
('PIDILITIND', 'Pidilite Industries Ltd.'), 
('PFC', 'Power Finance Corporation Ltd.'), 
('POWERGRID', 'Power Grid Corporation of India Ltd.'), 
('PNB', 'Punjab National Bank'), 
('RECLTD', 'REC Ltd.'), 
('RELIANCE', 'Reliance Industries Ltd.'), 
('SBICARD', 'SBI Cards and Payment Services Ltd.'), 
('SBILIFE', 'SBI Life Insurance Company Ltd.'), 
('SRF', 'SRF Ltd.'), 
('MOTHERSON', 'Samvardhana Motherson International Ltd.'), 
('SHREECEM', 'Shree Cement Ltd.'), 
('SHRIRAMFIN', 'Shriram Finance Ltd.'), 
('SIEMENS', 'Siemens Ltd.'), 
('SBIN', 'State Bank of India'), 
('SUNPHARMA', 'Sun Pharmaceutical Industries Ltd.'), 
('TVSMOTOR', 'TVS Motor Company Ltd.'), 
('TCS', 'Tata Consultancy Services Ltd.'), 
('TATACONSUM', 'Tata Consumer Products Ltd.'), 
('TATAMTRDVR', 'Tata Motors Ltd DVR'), 
('TATAMOTORS', 'Tata Motors Ltd.'), 
('TATAPOWER', 'Tata Power Co. Ltd.'), 
('TATASTEEL', 'Tata Steel Ltd.'), 
('TECHM', 'Tech Mahindra Ltd.'), 
('TITAN', 'Titan Company Ltd.'), 
('TORNTPHARM', 'Torrent Pharmaceuticals Ltd.'), 
('TRENT', 'Trent Ltd.'), 
('ULTRACEMCO', 'UltraTech Cement Ltd.'), 
('MCDOWELL-N', 'United Spirits Ltd.'), 
('VBL', 'Varun Beverages Ltd.'), 
('VEDL', 'Vedanta Ltd.'), 
('WIPRO', 'Wipro Ltd.'), 
('ZOMATO', 'Zomato Ltd.'), 
('ZYDUSLIFE', 'Zydus Lifesciences Ltd.');